CREATE TABLE [dbo].[T_PERSON] (
    [PERSON_ID]     BIGINT        IDENTITY (1, 1) NOT NULL,
    [FIRST_NAME]    NVARCHAR (20) NOT NULL,
    [LAST_NAME]     NVARCHAR (20) NOT NULL,
    [EMAIL_ADDRESS] NVARCHAR (50) NULL,
    PRIMARY KEY CLUSTERED ([PERSON_ID] ASC)
);

