CREATE TABLE [dbo].[T_TEAM_PERSON_MAP] (
    [TEAM_PERSON_ID] BIGINT IDENTITY (1, 1) NOT NULL,
    [PERSON_ID]      BIGINT NOT NULL,
    [TEAM_ID]        BIGINT NOT NULL,
    PRIMARY KEY CLUSTERED ([TEAM_PERSON_ID] ASC)
);

